### ISSUE TITLE
SheetMetal v1.0 Milestones

### ISSUE THREAD

**Issue by shaise** [shaise/FreeCAD_SheetMetal#412]
### Milestones for ver 1.0

- [x] Remove code duplication. Add helper function for common tasks
- [x] Add GUI (task panel) to all functions
- [x] Sticky parameter values when a function is reused
- [ ] Add and edit tool tips
- [ ] Make moving the tip and inserting of sheetmetal features in PD work 
- [x] Parametrize unfolding (using manual update button, because it is slow)
- [ ] Update translation files on crowdin
- [ ] Make the WB TNP - aware? https://github.com/FreeCAD/FreeCAD/issues/18671
- [x] AddBase: keep sketch visible #421 
- [x] Properly propagate object's material. 
- [x] Make forming tool easier to use + add missing task panel
- [x] Add cutout missing task panel
- [x] Solid body/Shell to SheetMetal #385 
- [x] New unfolder by @alexneufeld !
- [x] Option to detach the unfolded object from the body
- [x] Improve flange command by @sheetmetalman 
- [x] Add option to delete edges from multi selections in the task panel
- [x] Add sketch command to the toolbar. Issue #481 
- [ ] Allow commands to be used without prior selection. Issue #480 
- [x] Split functionality of `SheetMetal_Extrude`  command. Issue #482 
- [ ] Add intersection clearance for standard extend (similar to extend by sketch). Issue #560  

### Other milestones:
- [ ] Add preview geometry. [Based on freecad PR](https://github.com/FreeCAD/FreeCAD/pull/29641)

**Comment by shaise** [comment]
@hasecilu,
I have implemented GUI panels to all missing function, Can you please update Crowdin with these changes?

**Comment by hasecilu** [comment]
Hi, file has been updated.

**Comment by ma00aem** [comment]
How can i test this release? Is it updated automatically or how to download it?

**Comment by shaise** [comment]
Everything marked "V" are already in the latest release.

**Comment by luzpaz** [comment]
@shaise any plan to roll this out around the time of the  the FreeCAD 1.1 release ?

**Comment by shaise** [comment]
out of all the issues, the TNP is the most important. It looks like someone is working on it.
Regarding other milestones, I can try to attend some, but even if I dont, if TNP is fixed, I think we can mark it as V1.0

**Comment by luzpaz** [comment]
> Regarding other milestones, I can try to attend some, but even if I dont, if TNP is fixed, I think we can mark it as V1.0

Makes absolute sense :+1:

Edit: what about the smaller UI stuff like tooltips and translations? When do you want to pull the trigger on those ?

**Comment by luzpaz** [comment]
@alexneufeld any interest in hitting one of these before the 1.0 release?

**Comment by luzpaz** [comment]
>  Add option to delete edges from multi selections in the task panel  

@shaise should we create a ticket for this ?

**Comment by shaise** [comment]
@luzpaz , this is not a critical feature. do we need a separate ticket for it?

**Comment by luzpaz** [comment]
Just to be able to track it but if you don't deem it necessary, then so be it. 😉

**Comment by luzpaz** [comment]
@shaise we're going to get another influx of users after 1.1 is released. What's the probability that the remaining issues here get solved (or bumped to the next version of Sheetmetal) ?

**Comment by shaise** [comment]
I need to check the state of the TNP issues - thats my main blocker. For other issues I can push it to the next versions.
